version: "3.9"
services:
  micro_ros_agent:
    extends:
      file: docker-compose-agent.yml
      service: micro_ros_agent
    environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
